#!/bin/bash
set -u

print_help() {
    echo "no help available, sorry"
}

while true; do
    case "${1:-}" in
    -h|--help)
        print_help
        exit 0
        ;;
    *)
        break
        ;;
    esac
    shift
done

cd "$(dirname "$0")" || exit 1
export PYTHONPATH="$(pwd)"

popd; pushd tests/rule
rm -f build.ninja file
python3 anvil_gen.py
test -e build.ninja || exit 1
ninja file || exit 1
test -e file || exit 1

popd; pushd tests/empty
rm -f build.ninja
python3 anvil_gen.py
test -e build.ninja || exit 1
